### ISSUE TITLE
Friendly become Enemy Lua Error

### ISSUE THREAD

**Issue by behub-torch** [Tercioo/Plater-Nameplates#113]
### **Game and Plater version**
WoW: 9.2.0.42979
Plater: Plater-v347-17-gfbfe733-Retail

### **Describe the bug**
During raid on either Lords of Dread or Jailer, when players become enemies or MC'd I get spammed with lua errors.

### **Lua Error**

**Example 1:**
```50x SharedXML\PixelUtil.lua:44: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: NamePlate3PlaterUnitFrameExtraIconRowIcon1:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@SharedXML\PixelUtil.lua"]:44: in function `SetPoint'
[string "@Plater\libs\DF\panel.lua"]:5274: in function `GetIcon'
[string "@Plater\libs\DF\panel.lua"]:5303: in function `SetIcon'
[string "@Plater\Plater_Auras.lua"]:1138: in function `AddExtraIcon'
[string "@Plater\Plater_Auras.lua"]:1468: in function `UpdateAuras_Automatic'
[string "@Plater\Plater-Plater-v347-16-gf401781-Retail.lua"]:5804: in function <Plater\Plater.lua:5662>

Locals:
(*temporary) = NamePlate3PlaterUnitFrameExtraIconRowIcon1 {
 BottomLeftCorner = <unnamed> {
 }
 spellId = 127797
 duration = 0
 Border = <unnamed> {
 }
 expirationTime = 0
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:382
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:414
 RightEdge = <unnamed> {
 }
 Texture = <unnamed> {
 }
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:286
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:321
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:274
 CountdownText = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:401
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:339
 canStealOrPurge = false
 Cooldown = NamePlate3PlaterUnitFrameExtraIconRowIcon1IconCooldown1 {
 }
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:258
 Center = <unnamed> {
 }
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:270
 PixelSnapDisabled = true
 spellName = "Ursol's Vortex"
 parentIconRow = NamePlate3PlaterUnitFrameExtraIconRow {
 }
 isBuff = false
 lastUpdateCooldown = 16765.828000
 count = 0
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:206
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:174
 TopRightCorner = <unnamed> {
 }
 timeRemaining = -16765.828000
 startTime = 0
 TopLeftCorner = <unnamed> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:180
 0 = <userdata>
 caster = "raid23"
 TopEdge = <unnamed> {
 }
 backdropInfo = <table> {
 }
 __PlaterGlowFrame = <unnamed> {
 }
 Desc = <unnamed> {
 }
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:144
 StackText = <unnamed> {
 }
 BottomEdge = <unnamed> {
 }
 filter = "HARMFUL"
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:238
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:391
 LeftEdge = <unnamed> {
 }
 BottomRightCorner = <unnamed> {
 }
}
(*temporary) = "left"
(*temporary) = NamePlate3PlaterUnitFrameExtraIconRowIcon2 {
 BottomLeftCorner = <unnamed> {
 }
 spellId = 365466
 duration = 20
 Border = <unnamed> {
 }
 expirationTime = 16783.095000
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:382
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:414
 RightEdge = <unnamed> {
 }
 Texture = <unnamed> {
 }
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:286
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:321
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:274
 CountdownText = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:401
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:339
 canStealOrPurge = true
 Cooldown = NamePlate3PlaterUnitFrameExtraIconRowIcon2IconCooldown2 {
 }
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:258
 Center = <unnamed> {
 }
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:270
 PixelSnapDisabled = true
 spellName = "Inner Hatred"
 parentIconRow = NamePlate3PlaterUnitFrameExtraIconRow {
 }
 isBuff = true
 lastUpdateCooldown = 16765.828000
 count = 0
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:206
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:174
 TopRightCorner = <unnamed> {
 }
 timeRemaining = 17.267000
 startTime = 16763.095000
 debuffType = "Magic"
 TopLeftCorner = <unnamed> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:180
 0 = <userdata>
 TopEdge = <unnamed> {
 }
 backdropInfo = <table> {
 }
 __PlaterGlowFrame = <unnamed> {
 }
 Desc = <unnamed> {
 }
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:144
 StackText = <unnamed> {
 }
 BottomEdge = <unnamed> {
 }
 filter = "HELPFUL"
 SetupPieceVisuals = <function> d
```

**Example 2:**
```78x SharedXML\PixelUtil.lua:44: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: NamePlate30PlaterUnitFrameExtraIconRowIcon1:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@SharedXML\PixelUtil.lua"]:44: in function `SetPoint'
[string "@Plater\libs\DF\panel.lua"]:5274: in function `GetIcon'
[string "@Plater\libs\DF\panel.lua"]:5303: in function `SetIcon'
[string "@Plater\Plater_Auras.lua"]:1138: in function `AddExtraIcon'
[string "@Plater\Plater_Auras.lua"]:1468: in function `UpdateAuras_Automatic'
[string "@Plater\Plater-Plater-v347-17-gfbfe733-Retail.lua"]:5804: in function <Plater\Plater.lua:5662>

Locals:
Skipped (In Encounter)
```

### **Other Information**
Have not tried with just Plater loaded. Hasn't been occurring up until recently.

Is there a way to enable further debugging to see if a recently updated mod / script is contributing to this error?

**Comment by cont1nuity** [comment]
No worries. Will probably be fixed with the next alpha version.

**Comment by behub-torch** [comment]
Last night during heroic Jailer, once the charms went out even with the newer alpha the error still appeared. Not sure if you wanted a new ticket open or not.

```
33x SharedXML\PixelUtil.lua:44: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: NamePlate10PlaterUnitFrameExtraIconRowIcon3:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@SharedXML\PixelUtil.lua"]:44: in function `SetPoint'
[string "@Details\Libs\DF\panel.lua"]:5274: in function `GetIcon'
[string "@Details\Libs\DF\panel.lua"]:5303: in function `SetIcon'
[string "@Plater\Plater_Auras.lua"]:1140: in function `AddExtraIcon'
[string "@Plater\Plater_Auras.lua"]:1469: in function `UpdateAuras_Automatic'
[string "@Plater\Plater-Plater-v347-21-g152fb29-Retail.lua"]:5804: in function <Plater\Plater.lua:5662>

Locals:
Skipped (In Encounter)
```

```
56x SharedXML\PixelUtil.lua:44: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: NamePlate10PlaterUnitFrameExtraIconRowIcon2:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@SharedXML\PixelUtil.lua"]:44: in function `SetPoint'
[string "@Details\Libs\DF\panel.lua"]:5274: in function `GetIcon'
[string "@Details\Libs\DF\panel.lua"]:5303: in function `SetIcon'
[string "@Plater\Plater_Auras.lua"]:1140: in function `AddExtraIcon'
[string "@Plater\Plater_Auras.lua"]:1469: in function `UpdateAuras_Automatic'
[string "@Plater\Plater-Plater-v347-21-g152fb29-Retail.lua"]:5804: in function <Plater\Plater.lua:5662>

Locals:
Skipped (In Encounter)
```

```
23x SharedXML\PixelUtil.lua:44: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: NamePlate13PlaterUnitFrameExtraIconRowIcon2:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@SharedXML\PixelUtil.lua"]:44: in function `SetPoint'
[string "@Details\Libs\DF\panel.lua"]:5274: in function `GetIcon'
[string "@Details\Libs\DF\panel.lua"]:5303: in function `SetIcon'
[string "@Plater\Plater_Auras.lua"]:1140: in function `AddExtraIcon'
[string "@Plater\Plater_Auras.lua"]:1469: in function `UpdateAuras_Automatic'
[string "@Plater\Plater-Plater-v347-21-g152fb29-Retail.lua"]:5804: in function <Plater\Plater.lua:5662>

Locals:
Skipped (In Encounter)
```

```
16x SharedXML\PixelUtil.lua:44: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: NamePlate13PlaterUnitFrameExtraIconRowIcon1:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@SharedXML\PixelUtil.lua"]:44: in function `SetPoint'
[string "@Details\Libs\DF\panel.lua"]:5274: in function `GetIcon'
[string "@Details\Libs\DF\panel.lua"]:5303: in function `SetIcon'
[string "@Plater\Plater_Auras.lua"]:1140: in function `AddExtraIcon'
[string "@Plater\Plater_Auras.lua"]:1469: in function `UpdateAuras_Automatic'
[string "@Plater\Plater-Plater-v347-21-g152fb29-Retail.lua"]:5804: in function <Plater\Plater.lua:5662>
```

As you can see in the log it is version 'Plater-Plater-v347-21-g152fb29', but I have of course updated to the newer one earlier but that just had combo point fixes.

**Comment by cont1nuity** [comment]
Should be fixed with this evenings alpha version: [Plater-v347-26-g074ba90-Retail](https://www.curseforge.com/wow/addons/plater-nameplates/files/3734436)
